export const FETCH_VENDOR_ITEMS = 'FETCH_VENDOR_ITEMS';
export const ITEMS_RECEIVED = 'ITEMS_RECEIVED';
export const ITEMS_FETCH_FAILED = 'ITEMS_FETCH_FAILED';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
