export const SELECT_VENDOR = 'SELECT_VENDOR';
export const FETCH_VENDOR_ITEMS = 'FETCH_VENDOR_ITEMS';
export const ITEMS_RECEIVED = 'ITEMS_RECEIVED';
export const ITEMS_FETCH_FAILED = 'ITEMS_FETCH_FAILED';
